/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Report the API's current health status and version.
         *
         *     Returns:
         *         HealthResponse: An object with status set to "healthy" and the
         *             running application version.
         *
         *     Example:
         *         >>> health_check()
         *         HealthResponse(status='healthy', version='1.0.0')
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Prompts
         * @description List prompts, optionally filtered by collection, search text,
         *     and/or tags.
         *
         *     Results are sorted by creation date, newest first.
         *
         *     Args:
         *         collection_id (Optional[str]): If provided, only prompts belonging
         *             to this collection are included.
         *         search (Optional[str]): If provided, only prompts whose title or
         *             description contain this text (case-insensitive) are included.
         *         tags (Optional[str]): If provided, a comma-separated list of tag
         *             names; only prompts carrying at least one of them (OR match,
         *             case-insensitive) are included.
         *
         *     Returns:
         *         PromptList: The matching prompts and the total count.
         *
         *     Example:
         *         >>> list_prompts(search="email")
         *         PromptList(prompts=[...], total=2)
         */
        get: operations["list_prompts_prompts_get"];
        put?: never;
        /**
         * Create Prompt
         * @description Create a new prompt.
         *
         *     Args:
         *         prompt_data (PromptCreate): The title, content, and optional
         *             description and collection_id for the new prompt.
         *
         *     Returns:
         *         Prompt: The newly created prompt, with a generated id and
         *             creation/update timestamps.
         *
         *     Raises:
         *         HTTPException: With status 400 if prompt_data.collection_id is
         *             provided but does not correspond to an existing collection.
         *
         *     Example:
         *         >>> create_prompt(PromptCreate(title="Greeting", content="Hello!"))
         *         Prompt(id='...', title='Greeting', content='Hello!', ...)
         */
        post: operations["create_prompt_prompts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prompts/{prompt_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Prompt
         * @description Retrieve a prompt by a unique identifier/
         *     Args:
         *         prompt_id: The unique identifier fo the prompt to retrieve.
         *     Returns:
         *         The prompt if found, raises exception otherwise.
         *     Raises:
         *         HTTPException: If prompt_id is not found.
         */
        get: operations["get_prompt_prompts__prompt_id__get"];
        /**
         * Update Prompt
         * @description Updates an existing prompt by its ID with new field values.
         *
         *     Preserves the original prompt's ID and creation timestamp. The
         *     updated_at timestamp is set to the current time.
         *
         *     Args:
         *         prompt_id: The unique identifier of the prompt to update.
         *         prompt_data: A PromptUpdate object containing the new title,
         *             content, description, and optional collection_id.
         *
         *     Returns:
         *         The updated Prompt object as persisted by storage.
         *
         *     Raises:
         *         HTTPException: With status 404 if no prompt with prompt_id exists.
         *         HTTPException: With status 400 if prompt_data.collection_id is
         *             provided but does not correspond to an existing collection.
         */
        put: operations["update_prompt_prompts__prompt_id__put"];
        post?: never;
        /**
         * Delete Prompt
         * @description Delete a prompt by its unique identifier.
         *
         *     Args:
         *         prompt_id (str): The unique identifier of the prompt to delete.
         *
         *     Returns:
         *         None: No content is returned on successful deletion.
         *
         *     Raises:
         *         HTTPException: With status 404 if no prompt with prompt_id exists.
         *
         *     Example:
         *         >>> delete_prompt("abc-123")
         */
        delete: operations["delete_prompt_prompts__prompt_id__delete"];
        options?: never;
        head?: never;
        /**
         * Patch Prompt
         * @description Partially updates an existing prompt, changing only the provided fields.
         *
         *     Fields omitted from the request body are left unchanged. The updated_at
         *     timestamp is always refreshed on a successful update.
         *
         *     Args:
         *         prompt_id: The unique identifier of the prompt to update.
         *         prompt_data: A PromptPatch object containing any subset of title,
         *             content, description, and collection_id to update.
         *
         *     Returns:
         *         The updated Prompt object as persisted by storage.
         *
         *     Raises:
         *         HTTPException: With status 404 if no prompt with prompt_id exists.
         *         HTTPException: With status 400 if collection_id is explicitly provided
         *             and does not correspond to an existing collection.
         */
        patch: operations["patch_prompt_prompts__prompt_id__patch"];
        trace?: never;
    };
    "/prompts/{prompt_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Prompt Versions
         * @description List a prompt's version history, newest first.
         *
         *     Args:
         *         prompt_id (str): The unique identifier of the prompt whose
         *             version history should be listed.
         *
         *     Returns:
         *         PromptVersionList: The prompt's versions, ordered by
         *             version_number descending, and the total count.
         *
         *     Raises:
         *         HTTPException: With status 404 if no prompt with prompt_id exists.
         *
         *     Example:
         *         >>> list_prompt_versions("abc-123")
         *         PromptVersionList(versions=[...], total=3)
         */
        get: operations["list_prompt_versions_prompts__prompt_id__versions_get"];
        put?: never;
        /**
         * Create Prompt Version
         * @description Manually save a labeled checkpoint of a prompt's current state.
         *
         *     Args:
         *         prompt_id (str): The unique identifier of the prompt to
         *             checkpoint.
         *         version_data (PromptVersionCreate): The optional label for the
         *             new checkpoint.
         *
         *     Returns:
         *         PromptVersion: The newly created version, capturing the prompt's
         *             current title, content, and description, with version_number
         *             set to one more than the highest existing version for this
         *             prompt.
         *
         *     Raises:
         *         HTTPException: With status 404 if no prompt with prompt_id exists.
         *
         *     Example:
         *         >>> create_prompt_version("abc-123", PromptVersionCreate(label="before rewrite"))
         *         PromptVersion(prompt_id='abc-123', label='before rewrite', ...)
         */
        post: operations["create_prompt_version_prompts__prompt_id__versions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prompts/{prompt_id}/versions/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Prompt Version
         * @description Retrieve one specific version of a prompt.
         *
         *     Args:
         *         prompt_id (str): The unique identifier of the prompt the version
         *             belongs to.
         *         version_id (str): The unique identifier of the version to
         *             retrieve.
         *
         *     Returns:
         *         PromptVersion: The matching version.
         *
         *     Raises:
         *         HTTPException: With status 404 if prompt_id does not exist, if
         *             version_id does not exist, or if version_id exists but does
         *             not belong to prompt_id.
         *
         *     Example:
         *         >>> get_prompt_version("abc-123", "3b1c...")
         *         PromptVersion(id='3b1c...', prompt_id='abc-123', ...)
         */
        get: operations["get_prompt_version_prompts__prompt_id__versions__version_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Prompt Version
         * @description Delete one specific version of a prompt.
         *
         *     Args:
         *         prompt_id (str): The unique identifier of the prompt the version
         *             belongs to.
         *         version_id (str): The unique identifier of the version to delete.
         *
         *     Returns:
         *         None: No content is returned on successful deletion.
         *
         *     Raises:
         *         HTTPException: With status 404 if prompt_id does not exist, if
         *             version_id does not exist, or if version_id exists but does
         *             not belong to prompt_id.
         *
         *     Example:
         *         >>> delete_prompt_version("abc-123", "3b1c...")
         */
        delete: operations["delete_prompt_version_prompts__prompt_id__versions__version_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prompts/{prompt_id}/versions/{version_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore Prompt Version
         * @description Restore a prompt's title, content, and description to a past version.
         *
         *     The prompt's state immediately before the restore is itself saved as
         *     a new, unlabeled version, so the restore can be undone the same way
         *     any other edit can. The prompt's collection_id is left unchanged.
         *
         *     Args:
         *         prompt_id (str): The unique identifier of the prompt to restore.
         *         version_id (str): The unique identifier of the version to
         *             restore to.
         *
         *     Returns:
         *         Prompt: The updated prompt, with updated_at refreshed.
         *
         *     Raises:
         *         HTTPException: With status 404 if prompt_id does not exist, if
         *             version_id does not exist, or if version_id exists but does
         *             not belong to prompt_id.
         *
         *     Example:
         *         >>> restore_prompt_version("abc-123", "3b1c...")
         *         Prompt(id='abc-123', title='Customer follow-up email', ...)
         */
        post: operations["restore_prompt_version_prompts__prompt_id__versions__version_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tags
         * @description List every tag currently in use, each with its prompt_count.
         *
         *     Returns:
         *         TagList: All stored tags and the total count.
         *
         *     Example:
         *         >>> list_tags()
         *         TagList(tags=[...], total=2)
         */
        get: operations["list_tags_tags_get"];
        put?: never;
        /**
         * Create Tag
         * @description Explicitly create a new tag.
         *
         *     Unlike the implicit get-or-create that happens when tagging a prompt,
         *     this call is a deliberate "create a new tag" request and rejects a
         *     name collision rather than silently reusing the existing tag.
         *
         *     Args:
         *         tag_data (TagCreate): The name for the new tag.
         *
         *     Returns:
         *         Tag: The newly created tag.
         *
         *     Raises:
         *         HTTPException: With status 409 if a tag with this name (in any
         *             capitalization) already exists.
         *
         *     Example:
         *         >>> create_tag(TagCreate(name="needs-review"))
         *         Tag(name='needs-review', ...)
         */
        post: operations["create_tag_tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tag
         * @description Retrieve a tag by its unique identifier.
         *
         *     Args:
         *         tag_id (str): The unique identifier of the tag to retrieve.
         *
         *     Returns:
         *         Tag: The matching tag, with its current prompt_count.
         *
         *     Raises:
         *         HTTPException: With status 404 if no tag with tag_id exists.
         *
         *     Example:
         *         >>> get_tag("abc-123")
         *         Tag(id='abc-123', name='marketing', ...)
         */
        get: operations["get_tag_tags__tag_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Tag
         * @description Delete a tag by its unique identifier.
         *
         *     Removes the tag from every prompt that carried it; those prompts are
         *     not deleted and their other fields are unaffected.
         *
         *     Args:
         *         tag_id (str): The unique identifier of the tag to delete.
         *
         *     Returns:
         *         None: No content is returned on successful deletion.
         *
         *     Raises:
         *         HTTPException: With status 404 if no tag with tag_id exists.
         *
         *     Example:
         *         >>> delete_tag("abc-123")
         */
        delete: operations["delete_tag_tags__tag_id__delete"];
        options?: never;
        head?: never;
        /**
         * Rename Tag
         * @description Rename an existing tag.
         *
         *     The new name is reflected on every prompt that carries this tag,
         *     since a prompt's tags are stored as a link to the Tag record, not a
         *     copy of its name.
         *
         *     Args:
         *         tag_id (str): The unique identifier of the tag to rename.
         *         tag_data (TagRename): The tag's new name.
         *
         *     Returns:
         *         Tag: The renamed tag.
         *
         *     Raises:
         *         HTTPException: With status 404 if no tag with tag_id exists.
         *         HTTPException: With status 409 if the new name collides (case-
         *             insensitively) with a *different* existing tag. Renaming a
         *             tag to its own current name (a case-only change) is not
         *             treated as a collision.
         *
         *     Example:
         *         >>> rename_tag("abc-123", TagRename(name="needs-final-review"))
         *         Tag(id='abc-123', name='needs-final-review', ...)
         */
        patch: operations["rename_tag_tags__tag_id__patch"];
        trace?: never;
    };
    "/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Collections
         * @description List all collections.
         *
         *     Returns:
         *         CollectionList: All stored collections and the total count.
         *
         *     Example:
         *         >>> list_collections()
         *         CollectionList(collections=[...], total=3)
         */
        get: operations["list_collections_collections_get"];
        put?: never;
        /**
         * Create Collection
         * @description Create a new collection.
         *
         *     Args:
         *         collection_data (CollectionCreate): The name and optional
         *             description for the new collection.
         *
         *     Returns:
         *         Collection: The newly created collection, with a generated id and
         *             creation timestamp.
         *
         *     Example:
         *         >>> create_collection(CollectionCreate(name="My Collection"))
         *         Collection(id='...', name='My Collection', ...)
         */
        post: operations["create_collection_collections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections/{collection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Collection
         * @description Retrieve a collection by its unique identifier.
         *
         *     Args:
         *         collection_id (str): The unique identifier of the collection to
         *             retrieve.
         *
         *     Returns:
         *         Collection: The matching collection.
         *
         *     Raises:
         *         HTTPException: With status 404 if no collection with collection_id
         *             exists.
         *
         *     Example:
         *         >>> get_collection("abc-123")
         *         Collection(id='abc-123', name='My Collection', ...)
         */
        get: operations["get_collection_collections__collection_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Collection
         * @description Delete a collection by its unique identifier.
         *
         *     Any prompts assigned to this collection are unassigned (their
         *     collection_id is set to None) rather than deleted, before the
         *     collection itself is removed.
         *
         *     Args:
         *         collection_id (str): The unique identifier of the collection to
         *             delete.
         *
         *     Returns:
         *         None: No content is returned on successful deletion.
         *
         *     Raises:
         *         HTTPException: With status 404 if no collection with collection_id
         *             exists.
         *
         *     Example:
         *         >>> delete_collection("abc-123")
         */
        delete: operations["delete_collection_collections__collection_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Collection
         * @description Full collection schema, including server-generated fields.
         *
         *     Attributes:
         *         name (str): The collection's name, between 1 and 100 characters.
         *         description (Optional[str]): An optional description, up to 500
         *             characters.
         *         id (str): The collection's unique identifier, generated
         *             automatically.
         *         created_at (datetime): The UTC timestamp when the collection was
         *             created, set automatically.
         *
         *     Example:
         *         >>> collection = Collection(name="My Collection")
         *         >>> collection.name
         *         'My Collection'
         */
        Collection: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Id */
            id?: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** CollectionCreate */
        CollectionCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /**
         * CollectionList
         * @description Response schema for a paginated or filtered list of collections.
         *
         *     Attributes:
         *         collections (List[Collection]): The list of collections being
         *             returned.
         *         total (int): The total number of collections matching the query.
         *
         *     Example:
         *         >>> result = CollectionList(collections=[], total=0)
         *         >>> result.total
         *         0
         */
        CollectionList: {
            /** Collections */
            collections: components["schemas"]["Collection"][];
            /** Total */
            total: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Response schema for the API health check endpoint.
         *
         *     Attributes:
         *         status (str): The current health status of the service.
         *         version (str): The running version of the service.
         *
         *     Example:
         *         >>> health = HealthResponse(status="ok", version="1.0.0")
         *         >>> health.status
         *         'ok'
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * Prompt
         * @description Full prompt schema, including server-generated fields.
         *
         *     Attributes:
         *         title (str): The prompt's title, between 1 and 200 characters.
         *         content (str): The prompt's text content, at least 1 character.
         *         description (Optional[str]): An optional description, up to 500
         *             characters.
         *         collection_id (Optional[str]): The identifier of the collection
         *             this prompt belongs to, if any.
         *         id (str): The prompt's unique identifier, generated automatically.
         *         created_at (datetime): The UTC timestamp when the prompt was
         *             created, set automatically.
         *         updated_at (datetime): The UTC timestamp when the prompt was last
         *             updated, set automatically.
         *         tags (List[Tag]): The prompt's currently-attached tags, embedded
         *             in full. Defaults to an empty list.
         *
         *     Example:
         *         >>> prompt = Prompt(title="Greeting", content="Hello, world!")
         *         >>> prompt.title
         *         'Greeting'
         */
        Prompt: {
            /** Title */
            title: string;
            /** Content */
            content: string;
            /** Description */
            description?: string | null;
            /** Collection Id */
            collection_id?: string | null;
            /** Id */
            id?: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
            /** Tags */
            tags?: components["schemas"]["Tag"][];
        };
        /**
         * PromptCreate
         * @description Extends PromptBase with an optional list of tag names to attach.
         *
         *     Attributes:
         *         tags (Optional[List[str]]): Tag names to attach to the new
         *             prompt, resolved via case-insensitive get-or-create. Omitting
         *             this field means the prompt is created with no tags.
         */
        PromptCreate: {
            /** Title */
            title: string;
            /** Content */
            content: string;
            /** Description */
            description?: string | null;
            /** Collection Id */
            collection_id?: string | null;
            /** Tags */
            tags?: string[] | null;
        };
        /**
         * PromptList
         * @description Response schema for a paginated or filtered list of prompts.
         *
         *     Attributes:
         *         prompts (List[Prompt]): The list of prompts being returned.
         *         total (int): The total number of prompts matching the query.
         *
         *     Example:
         *         >>> result = PromptList(prompts=[], total=0)
         *         >>> result.total
         *         0
         */
        PromptList: {
            /** Prompts */
            prompts: components["schemas"]["Prompt"][];
            /** Total */
            total: number;
        };
        /**
         * PromptPatch
         * @description Schema for partially updating a prompt, with all fields optional.
         *
         *     Attributes:
         *         title (Optional[str]): The prompt's new title, between 1 and 200
         *             characters, if being updated.
         *         content (Optional[str]): The prompt's new text content, at least
         *             1 character, if being updated.
         *         description (Optional[str]): The prompt's new description, up to
         *             500 characters, if being updated.
         *         collection_id (Optional[str]): The identifier of the collection
         *             to move this prompt into, if being updated.
         *         tags (Optional[List[str]]): The prompt's complete tag set after
         *             this patch, resolved via case-insensitive get-or-create.
         *             Omitting this field entirely leaves the prompt's tags
         *             unchanged; including it (even as []) fully replaces them.
         *
         *     Example:
         *         >>> patch = PromptPatch(title="Updated Title")
         *         >>> patch.title
         *         'Updated Title'
         */
        PromptPatch: {
            /** Title */
            title?: string | null;
            /** Content */
            content?: string | null;
            /** Description */
            description?: string | null;
            /** Collection Id */
            collection_id?: string | null;
            /** Tags */
            tags?: string[] | null;
        };
        /**
         * PromptUpdate
         * @description Extends PromptBase with an optional list of tag names, full-replace.
         *
         *     Attributes:
         *         tags (Optional[List[str]]): The prompt's complete tag set after
         *             this update, resolved via case-insensitive get-or-create.
         *             Omitting this field means the prompt ends up with no tags
         *             (full replace, matching the rest of PUT's semantics).
         */
        PromptUpdate: {
            /** Title */
            title: string;
            /** Content */
            content: string;
            /** Description */
            description?: string | null;
            /** Collection Id */
            collection_id?: string | null;
            /** Tags */
            tags?: string[] | null;
        };
        /**
         * PromptVersion
         * @description A historical snapshot of a prompt's wording.
         *
         *     Attributes:
         *         id (str): The version's unique identifier, generated automatically.
         *         prompt_id (str): The identifier of the prompt this version
         *             belongs to.
         *         version_number (int): The version's sequential position among the
         *             prompt's versions, starting at 1 and never reused.
         *         title (str): The prompt's title at the time this version was
         *             captured.
         *         content (str): The prompt's content at the time this version was
         *             captured.
         *         description (Optional[str]): The prompt's description at the
         *             time this version was captured.
         *         label (Optional[str]): An optional user-supplied note; only set
         *             on manually-checkpointed versions.
         *         created_at (datetime): The UTC timestamp when this version was
         *             captured, set automatically.
         *
         *     Example:
         *         >>> version = PromptVersion(prompt_id="abc-123", version_number=1,
         *         ...     title="Greeting", content="Hello, world!")
         *         >>> version.version_number
         *         1
         */
        PromptVersion: {
            /** Id */
            id?: string;
            /** Prompt Id */
            prompt_id: string;
            /** Version Number */
            version_number: number;
            /** Title */
            title: string;
            /** Content */
            content: string;
            /** Description */
            description?: string | null;
            /** Label */
            label?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /**
         * PromptVersionCreate
         * @description Schema for manually saving a labeled checkpoint of a prompt.
         *
         *     Attributes:
         *         label (Optional[str]): An optional note describing this
         *             checkpoint, up to 100 characters.
         *
         *     Example:
         *         >>> checkpoint = PromptVersionCreate(label="before shortening")
         *         >>> checkpoint.label
         *         'before shortening'
         */
        PromptVersionCreate: {
            /** Label */
            label?: string | null;
        };
        /**
         * PromptVersionList
         * @description Response schema for a prompt's version history.
         *
         *     Attributes:
         *         versions (List[PromptVersion]): The prompt's versions.
         *         total (int): The total number of versions.
         *
         *     Example:
         *         >>> result = PromptVersionList(versions=[], total=0)
         *         >>> result.total
         *         0
         */
        PromptVersionList: {
            /** Versions */
            versions: components["schemas"]["PromptVersion"][];
            /** Total */
            total: number;
        };
        /**
         * Tag
         * @description Full tag schema, including server-generated fields.
         *
         *     Attributes:
         *         name (str): The tag's name, 1-50 characters after trimming.
         *         id (str): The tag's unique identifier, generated automatically.
         *         created_at (datetime): The UTC timestamp when the tag was
         *             created, set automatically.
         *         prompt_count (int): The number of prompts currently carrying this
         *             tag. Computed, not stored - populated wherever tags are
         *             listed.
         *
         *     Example:
         *         >>> tag = Tag(name="marketing")
         *         >>> tag.prompt_count
         *         0
         */
        Tag: {
            /** Name */
            name: string;
            /** Id */
            id?: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Prompt Count
             * @default 0
             */
            prompt_count: number;
        };
        /** TagCreate */
        TagCreate: {
            /** Name */
            name: string;
        };
        /**
         * TagList
         * @description Response schema for the full list of tags in use.
         *
         *     Attributes:
         *         tags (List[Tag]): Every tag currently in use.
         *         total (int): The total number of tags.
         *
         *     Example:
         *         >>> result = TagList(tags=[], total=0)
         *         >>> result.total
         *         0
         */
        TagList: {
            /** Tags */
            tags: components["schemas"]["Tag"][];
            /** Total */
            total: number;
        };
        /** TagRename */
        TagRename: {
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_prompts_prompts_get: {
        parameters: {
            query?: {
                collection_id?: string | null;
                search?: string | null;
                tags?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_prompt_prompts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Prompt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_prompt_prompts__prompt_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prompt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Prompt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_prompt_prompts__prompt_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prompt_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Prompt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_prompt_prompts__prompt_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prompt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_prompt_prompts__prompt_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prompt_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Prompt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_prompt_versions_prompts__prompt_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prompt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptVersionList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_prompt_version_prompts__prompt_id__versions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prompt_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptVersionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptVersion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_prompt_version_prompts__prompt_id__versions__version_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prompt_id: string;
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptVersion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_prompt_version_prompts__prompt_id__versions__version_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prompt_id: string;
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_prompt_version_prompts__prompt_id__versions__version_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prompt_id: string;
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Prompt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tags_tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagList"];
                };
            };
        };
    };
    create_tag_tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tag_tags__tag_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_tag_tags__tag_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_tag_tags__tag_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagRename"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_collections_collections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionList"];
                };
            };
        };
    };
    create_collection_collections_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Collection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_collection_collections__collection_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Collection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_collection_collections__collection_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
